# this is a kludge to install this package on debian systems
# behind a proxy server and until Elastic.co fixes their debian install repo. 
# It currently lacks a Release file and installing their repo breaks apt-get 
# so...this workaround 201808.17MeV

- name: getting logstash deb file (this may take a couple minutes)
  shell: "wget https://artifacts.elastic.co/downloads/logstash/logstash-6.3.2.deb"
  args:
    warn: false # set warn=false to prevent warning
    creates: logstash-6.3.2.deb
  register: logstash_wget_result
# - debug: var=logstash_wget_result

- name: installing deb file
  apt:
    deb: ./logstash-6.3.2.deb
    # deb: https://artifacts.elastic.co/downloads/logstash/logstash-6.3.2.deb
    state: present
    allow_unauthenticated: True
  when: not logstash_wget_result.failed
  register: logstash_deb_apt
# - debug: var=logstash_deb_apt.stdout_lines
