---
# tasks file for logstash

- include_role:
    name: java
- include_role: 
    name: repo-elk

# requires Java 8 + elk-repo first installed first
# kludge to install on debian systems
- include_tasks: roles/logstash/tasks/Debian-install.yml
  when: ansible_os_family == 'Debian'

# - name: install logstash RPM
#   package: name=logstash-2.4.0 state=present
- include_tasks: roles/logstash/tasks/RedHat-install.yml
  when: ansible_os_family == 'RedHat'

- name: logstash config files
  copy: src={{ item.src }} dest=/etc/logstash/conf.d/
  with_items:
    - { src: '10-messages.conf' }
    - { src: '10-staas-commit.conf' }
    - { src: '10-staas-galaxy.conf' }
    - { src: '10-staas-gc.conf' }
    - { src: '10-staas-hardware.conf' }
    - { src: '10-staas-heartbeat.conf' }
    - { src: '10-staas-mds.conf' }
    - { src: '10-staas-metering.conf' }
    - { src: '10-staas-reaper.conf' }
    - { src: '10-staas-replication.conf' }
    - { src: '10-staas-replicationAudit.conf' }
    - { src: '10-staas-stats.conf' }
    - { src: '10-staas-swift.conf' }
    - { src: '10-staas-telemetry.conf' }
    - { src: '10-staas-universe.conf' }
    - { src: '10-syslog.conf' }
    - { src: '20-staas-parsedate.conf' }
    - { src: '20-tags.conf' }
    - { src: '25-staas-hardware.conf' }
    - { src: '25-staas-javaService.conf' }
    - { src: '25-staas-swift.conf' }
    - { src: '25-staas-telemetry.conf' }
    - { src: '29-staas-cleanup.conf' }
    - { src: '30-output.conf' }
  notify:
    - restart_logstash_service

- name: create patterns config directory
  file:
    path: /etc/logstash/patterns
    state: directory
    owner: 'root'
    group: 'root'
    mode: 755

# NOTE: configuring the logstash 2.x conf.d directory and hash size
# depends on the OS, so do this in the right file for RH or DEB

# for logstash 5.x use this:
# - name: configure logstash.yml
#   blockinfile:
#     path: /etc/logstash/logstash.yml
#     backup: yes      
#     marker: '# -- {mark} ANSIBLE MANAGED BLOCK --'
#     content: |
#       slowlog.threshold.warn: 2s
#       slowlog.threshold.info: 1s
#       slowlog.threshold.debug: 500ms
#       slowlog.threshold.trace: 100ms
#   notify:
#     - restart_logstash_service

# Creating certs directories for SSL
- name: Creates SSL directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/pki/tls/certs
    - /etc/pki/tls/private

# Update SSL to restrict outside access
# there's some debate on where this file is supposed to go
# https://stackoverflow.com/questions/21477210/correct-location-of-openssl-cnf-file
# Ubuntu = /etc/ssl/openssl.cnf
# RHEL = /etc/pki/tls/openssl.cnf
# also, lineinfile won't accept a variable in the line argument, so use template

# Generate SSL certificates for Logstash
- name: Updating RHEL openssl file to restrict outside access
  block:
    - template: 
        src: openssl-rpm.cnf.j2  
        dest: /etc/pki/tls/openssl.cnf
        owner: root
        group: root
        mode: 0644
        backup: yes
      register: openssl_file
    - shell: grep 'subjectAltName=IP' /etc/pki/tls/openssl.cnf
      when: not openssl_file.failed
      register: grep_openssl
    - debug: var=grep_openssl.stdout_lines
    - shell: 'openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt'
  when: ansible_os_family == 'RedHat'

- name: Updating DEB openssl file to restrict outside access
  block:
    - template: 
        src: openssl-deb.cnf.j2   
        dest: /etc/ssl/openssl.cnf
        owner: root
        group: root
        mode: 0644
        backup: yes
      register: openssl_file
    - shell: grep 'subjectAltName=IP' /etc/ssl/openssl.cnf
      when: not openssl_file.failed
      register: grep_openssl
    - debug: var=grep_openssl.stdout_lines
    - shell: 'openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt'
  when: ansible_os_family == 'Debian'

- name: Configure beats, syslog, & elastic configuration files
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'beats-input.conf.j2',          dest: '/etc/logstash/conf.d/40-beats-input.conf' }
    - { src: '40-syslog.conf.j2',            dest: '/etc/logstash/conf.d/40-syslog-filter.conf' }
    - { src: 'elasticsearch-output.conf.j2', dest: '/etc/logstash/conf.d/50-elasticsearch-output.conf' }
  notify:
    - restart_logstash_service


- name: enable and run logstash
  service: name=logstash state=started enabled=yes
