# Install on CentOS 6+7
---

- hosts: all
  become: true
  # check_mode: yes  # yes=dry-run

  roles:
    # - common
    - repo-epel

  pre_tasks:

    - name: define traditional ethernet facts
      set_fact:
        ansible_eth: "{% set ansible_eth = ansible_eth|default([]) + [hostvars[inventory_hostname]['ansible_' + item]] %}{{ ansible_eth|list }}"
      when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
      with_items:
      - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"
    - debug: var=ansible_eth.1.ipv4.address
    - debug: var=ansible_host

- hosts: kibana
  become: true
  tasks:

  roles:
    - java
    - kibana