---
# tasks to setup kibana

# requires Java 8 + elk-repo first installed first
- name: install kibana
  package:
    name: kibana
    state: present

# put stuff in here to configure servie

- name: enable and run kibana
  service: name=kibana state=started enabled=yes
