---
# tasks to setup kibana

# requires Java 8 + elk-repo first installed first
- name: install kibana
  package:
    name: kibana
    state: present

# default is to limit access to localhost connections only
- name: Updating kibana config file
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: "server.host: {{ kibana_server_host }}"

- name: enable and run kibana
  service: name=kibana state=started enabled=yes
