# debian-specific tasks to setup and fetch the Elastic repo

# - name: install apt transport for https
#   apt:
#     name: apt-transport-https
#     update_cache: yes

- name: checking if ELK repo is already configured...
  stat: path=/etc/apt/sources.list.d/elastic-6.x.list
  register: elk_repofile_result
# - debug: var=elk_repofile_result

# us this to add separate repo instead of apt_repository
# https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
- name: add ELK repo
  copy:
    dest: /etc/apt/sources.list.d/elastic-6.x.list
    content: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    owner: root
    group: root
    mode: 0644
  when: not elk_repofile_result.stat.exists

# apt_key and get_url fails if using proxies as ansible only works with http proxies
# so copy the key file with curl and install it locally
# also, the debian version of this code doesn't seem to be reading the role defaults
# also command gives warning for "creates", so use "shell" module
- name: get ELK key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add - 
  args:
    warn: false
    creates: GPG-KEY-elasticsearch
  register: elk_key
