---
# tasks to setup elasticsearch

# requires Java 8 + elk-repo first installed first
- name: install elasticsearch
  package:
    name: elasticsearch
    state: present

# Update Elasticsearch config file (default: only allow localhost connections)
- name: update elasticsearch configs (restrict to localhost)
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: "network.host: {{ elasticsearch_network_host }}"
  notify:
    - restart_elasticsearch_service

- name: enable and run elasticsearch
  service: name=elasticsearch state=started enabled=yes